eureka:
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${service-registry.uri:http://dockerhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 3
    prefer-ip-address: true
    ip-address: ${external.ip:${spring.cloud.client.ipAddress:dockerhost}}
    metadataMap:
      instanceId: ${spring.application.instance_id:${random.value}}

logging:
  file: ${spring.application.name}.log